// Code generated by protoc-gen-go.
// source: protobuftest.proto
// DO NOT EDIT!

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	protobuftest.proto

It has these top-level messages:
	OpeningTx
	UpdateTx
	Fulfillment
	Envelope
	Channel
	Identity
	Peer
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type Envelope_Type int32

const (
	Envelope_OpeningTx         Envelope_Type = 0
	Envelope_OpeningTxProposal Envelope_Type = 1
	Envelope_UpdateTx          Envelope_Type = 2
	Envelope_UpdateTxProposal  Envelope_Type = 3
	Envelope_Fulfillment       Envelope_Type = 4
)

var Envelope_Type_name = map[int32]string{
	0: "OpeningTx",
	1: "OpeningTxProposal",
	2: "UpdateTx",
	3: "UpdateTxProposal",
	4: "Fulfillment",
}
var Envelope_Type_value = map[string]int32{
	"OpeningTx":         0,
	"OpeningTxProposal": 1,
	"UpdateTx":          2,
	"UpdateTxProposal":  3,
	"Fulfillment":       4,
}

func (x Envelope_Type) String() string {
	return proto.EnumName(Envelope_Type_name, int32(x))
}
func (Envelope_Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

type OpeningTx struct {
	ChannelID  string `protobuf:"bytes,1,opt,name=channelID" json:"channelID,omitempty"`
	Pubkey1    []byte `protobuf:"bytes,2,opt,name=pubkey1,proto3" json:"pubkey1,omitempty"`
	Pubkey2    []byte `protobuf:"bytes,3,opt,name=pubkey2,proto3" json:"pubkey2,omitempty"`
	Amount1    uint32 `protobuf:"varint,4,opt,name=amount1" json:"amount1,omitempty"`
	Amount2    uint32 `protobuf:"varint,5,opt,name=amount2" json:"amount2,omitempty"`
	HoldPeriod uint32 `protobuf:"varint,6,opt,name=holdPeriod" json:"holdPeriod,omitempty"`
}

func (m *OpeningTx) Reset()                    { *m = OpeningTx{} }
func (m *OpeningTx) String() string            { return proto.CompactTextString(m) }
func (*OpeningTx) ProtoMessage()               {}
func (*OpeningTx) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type UpdateTx struct {
	ChannelID      string                `protobuf:"bytes,1,opt,name=channelID" json:"channelID,omitempty"`
	NetTransfer    int64                 `protobuf:"zigzag64,2,opt,name=netTransfer" json:"netTransfer,omitempty"`
	SequenceNumber uint32                `protobuf:"varint,3,opt,name=sequenceNumber" json:"sequenceNumber,omitempty"`
	Fast           bool                  `protobuf:"varint,4,opt,name=fast" json:"fast,omitempty"`
	Conditions     []*UpdateTx_Condition `protobuf:"bytes,5,rep,name=conditions" json:"conditions,omitempty"`
}

func (m *UpdateTx) Reset()                    { *m = UpdateTx{} }
func (m *UpdateTx) String() string            { return proto.CompactTextString(m) }
func (*UpdateTx) ProtoMessage()               {}
func (*UpdateTx) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UpdateTx) GetConditions() []*UpdateTx_Condition {
	if m != nil {
		return m.Conditions
	}
	return nil
}

type UpdateTx_Condition struct {
	PresetCondition     uint32 `protobuf:"varint,1,opt,name=presetCondition" json:"presetCondition,omitempty"`
	ConditionalTransfer int64  `protobuf:"varint,2,opt,name=conditionalTransfer" json:"conditionalTransfer,omitempty"`
	Data                string `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *UpdateTx_Condition) Reset()                    { *m = UpdateTx_Condition{} }
func (m *UpdateTx_Condition) String() string            { return proto.CompactTextString(m) }
func (*UpdateTx_Condition) ProtoMessage()               {}
func (*UpdateTx_Condition) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1, 0} }

type Fulfillment struct {
	ChannelID string `protobuf:"bytes,1,opt,name=channelID" json:"channelID,omitempty"`
	Condition uint32 `protobuf:"varint,2,opt,name=condition" json:"condition,omitempty"`
	Data      string `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *Fulfillment) Reset()                    { *m = Fulfillment{} }
func (m *Fulfillment) String() string            { return proto.CompactTextString(m) }
func (*Fulfillment) ProtoMessage()               {}
func (*Fulfillment) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type Envelope struct {
	Type       Envelope_Type `protobuf:"varint,1,opt,name=type,enum=pb.Envelope_Type" json:"type,omitempty"`
	Payload    []byte        `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Signature1 []byte        `protobuf:"bytes,3,opt,name=signature1,proto3" json:"signature1,omitempty"`
	Signature2 []byte        `protobuf:"bytes,4,opt,name=signature2,proto3" json:"signature2,omitempty"`
}

func (m *Envelope) Reset()                    { *m = Envelope{} }
func (m *Envelope) String() string            { return proto.CompactTextString(m) }
func (*Envelope) ProtoMessage()               {}
func (*Envelope) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type Channel struct {
	ChannelID string      `protobuf:"bytes,1,opt,name=channelID" json:"channelID,omitempty"`
	OpeningTx *OpeningTx  `protobuf:"bytes,2,opt,name=openingTx" json:"openingTx,omitempty"`
	UpdateTxs []*UpdateTx `protobuf:"bytes,3,rep,name=updateTxs" json:"updateTxs,omitempty"`
}

func (m *Channel) Reset()                    { *m = Channel{} }
func (m *Channel) String() string            { return proto.CompactTextString(m) }
func (*Channel) ProtoMessage()               {}
func (*Channel) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Channel) GetOpeningTx() *OpeningTx {
	if m != nil {
		return m.OpeningTx
	}
	return nil
}

func (m *Channel) GetUpdateTxs() []*UpdateTx {
	if m != nil {
		return m.UpdateTxs
	}
	return nil
}

type Identity struct {
	Nickname string   `protobuf:"bytes,1,opt,name=nickname" json:"nickname,omitempty"`
	Pubkey   []byte   `protobuf:"bytes,2,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	Privkey  []byte   `protobuf:"bytes,3,opt,name=privkey,proto3" json:"privkey,omitempty"`
	Channels []string `protobuf:"bytes,4,rep,name=channels" json:"channels,omitempty"`
}

func (m *Identity) Reset()                    { *m = Identity{} }
func (m *Identity) String() string            { return proto.CompactTextString(m) }
func (*Identity) ProtoMessage()               {}
func (*Identity) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type Peer struct {
	Nickname string   `protobuf:"bytes,1,opt,name=nickname" json:"nickname,omitempty"`
	Pubkey   []byte   `protobuf:"bytes,2,opt,name=pubkey,proto3" json:"pubkey,omitempty"`
	Channels []string `protobuf:"bytes,3,rep,name=channels" json:"channels,omitempty"`
}

func (m *Peer) Reset()                    { *m = Peer{} }
func (m *Peer) String() string            { return proto.CompactTextString(m) }
func (*Peer) ProtoMessage()               {}
func (*Peer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func init() {
	proto.RegisterType((*OpeningTx)(nil), "pb.OpeningTx")
	proto.RegisterType((*UpdateTx)(nil), "pb.UpdateTx")
	proto.RegisterType((*UpdateTx_Condition)(nil), "pb.UpdateTx.Condition")
	proto.RegisterType((*Fulfillment)(nil), "pb.Fulfillment")
	proto.RegisterType((*Envelope)(nil), "pb.Envelope")
	proto.RegisterType((*Channel)(nil), "pb.Channel")
	proto.RegisterType((*Identity)(nil), "pb.Identity")
	proto.RegisterType((*Peer)(nil), "pb.Peer")
	proto.RegisterEnum("pb.Envelope_Type", Envelope_Type_name, Envelope_Type_value)
}

var fileDescriptor0 = []byte{
	// 543 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x94, 0xdf, 0x6e, 0xd3, 0x4c,
	0x10, 0xc5, 0x3f, 0xc7, 0xfe, 0xd2, 0x78, 0x92, 0xb4, 0xe9, 0x00, 0x95, 0x55, 0x21, 0x54, 0x59,
	0x02, 0x45, 0x20, 0x45, 0xc4, 0x48, 0xbc, 0x40, 0x01, 0xa9, 0x37, 0x10, 0xad, 0x02, 0x77, 0x5c,
	0xac, 0xe3, 0x49, 0x6b, 0xd5, 0xd9, 0x35, 0xf6, 0xba, 0x22, 0xe2, 0x86, 0x57, 0xe2, 0x9a, 0x77,
	0xe2, 0x19, 0xf0, 0x6e, 0xfc, 0x2f, 0x55, 0xa5, 0x48, 0xdc, 0xf9, 0xcc, 0xcf, 0x9a, 0x39, 0x33,
	0x39, 0x0e, 0x60, 0x9a, 0x49, 0x25, 0xc3, 0x62, 0xad, 0x28, 0x57, 0x33, 0x23, 0xb0, 0x97, 0x86,
	0xfe, 0x2f, 0x0b, 0xdc, 0x4f, 0x29, 0x89, 0x58, 0x5c, 0x2f, 0xbf, 0xe3, 0x53, 0x70, 0x57, 0x37,
	0x5c, 0x08, 0x4a, 0xae, 0xde, 0x79, 0xd6, 0x85, 0x35, 0x75, 0x59, 0x5b, 0x40, 0x0f, 0x8e, 0xd2,
	0x22, 0xbc, 0xa5, 0xed, 0xdc, 0xeb, 0x95, 0x6c, 0xc4, 0x6a, 0xd9, 0x92, 0xc0, 0xb3, 0xbb, 0x24,
	0xd0, 0x84, 0x6f, 0x64, 0x21, 0xd4, 0xdc, 0x73, 0x4a, 0x32, 0x66, 0xb5, 0x6c, 0x49, 0xe0, 0xfd,
	0xdf, 0x25, 0x01, 0x3e, 0x03, 0xb8, 0x91, 0x49, 0xb4, 0xa0, 0x2c, 0x96, 0x91, 0xd7, 0x37, 0xb0,
	0x53, 0xf1, 0x7f, 0xf7, 0x60, 0xf0, 0x39, 0x8d, 0xb8, 0xa2, 0x83, 0x96, 0x2f, 0x60, 0x28, 0x48,
	0x2d, 0x33, 0x2e, 0xf2, 0x35, 0x65, 0xc6, 0x36, 0xb2, 0x6e, 0x09, 0x5f, 0xc0, 0x71, 0x4e, 0xdf,
	0x0a, 0x12, 0x2b, 0xfa, 0x58, 0x6c, 0xc2, 0xf2, 0x25, 0xdb, 0x0c, 0xbc, 0x57, 0x45, 0x04, 0x67,
	0xcd, 0x73, 0x65, 0xb6, 0x18, 0x30, 0xf3, 0x8c, 0x6f, 0x01, 0x56, 0x52, 0x44, 0xb1, 0x8a, 0xa5,
	0xc8, 0xcb, 0x2d, 0xec, 0xe9, 0x30, 0x38, 0x9b, 0xa5, 0xe1, 0xac, 0x76, 0x37, 0xbb, 0xac, 0x31,
	0xeb, 0xbc, 0x79, 0xfe, 0x03, 0xdc, 0x06, 0xe0, 0x14, 0x4e, 0xd2, 0x8c, 0x72, 0x52, 0x4d, 0xc9,
	0xac, 0x31, 0x66, 0xf7, 0xcb, 0xf8, 0x1a, 0x1e, 0x35, 0x4d, 0x78, 0xb2, 0xb7, 0x94, 0xcd, 0x1e,
	0x42, 0xda, 0x74, 0x69, 0x84, 0x9b, 0x95, 0x5c, 0x66, 0x9e, 0xfd, 0xaf, 0x30, 0xfc, 0x50, 0x24,
	0xeb, 0x38, 0x49, 0x36, 0x24, 0xd4, 0x81, 0xfb, 0x69, 0xda, 0xd8, 0xea, 0x19, 0x5b, 0x6d, 0xe1,
	0xc1, 0xf6, 0x7f, 0x2c, 0x18, 0xbc, 0x17, 0x77, 0x94, 0xc8, 0x94, 0xf0, 0x39, 0x38, 0x6a, 0x9b,
	0x92, 0xe9, 0x7b, 0x1c, 0x9c, 0xea, 0xd3, 0xd4, 0x6c, 0xb6, 0x2c, 0x01, 0x33, 0xd8, 0xc4, 0x87,
	0x6f, 0x13, 0xc9, 0xa3, 0x26, 0x58, 0x3b, 0xa9, 0xa3, 0x90, 0xc7, 0xd7, 0x82, 0xab, 0x22, 0xa3,
	0x79, 0x95, 0xad, 0x4e, 0x65, 0x8f, 0x07, 0xe6, 0xb7, 0xe9, 0xf2, 0xc0, 0xe7, 0xe0, 0xe8, 0x39,
	0x38, 0xee, 0xa4, 0x7c, 0xf2, 0x1f, 0x3e, 0x81, 0xd3, 0x46, 0x2e, 0x32, 0x99, 0xca, 0x9c, 0x27,
	0x13, 0x0b, 0x47, 0x6d, 0xae, 0x26, 0x3d, 0x7c, 0x0c, 0x93, 0x5a, 0x35, 0xef, 0xd8, 0x78, 0xb2,
	0x77, 0xbe, 0x89, 0xe3, 0xff, 0xb4, 0xe0, 0xe8, 0x72, 0x77, 0xb0, 0x03, 0xc7, 0x7c, 0x05, 0xae,
	0xac, 0xa7, 0x9a, 0x45, 0x87, 0xc1, 0x58, 0x9f, 0xa4, 0xb1, 0xc2, 0x5a, 0x8e, 0x2f, 0xc1, 0x2d,
	0xaa, 0xe9, 0x79, 0xb9, 0xb8, 0x8e, 0xd6, 0xa8, 0x1b, 0x2d, 0xd6, 0x62, 0x5f, 0xc1, 0xe0, 0x2a,
	0x2a, 0xdd, 0xc4, 0x6a, 0x8b, 0xe7, 0x30, 0x10, 0xf1, 0xea, 0x56, 0xf0, 0x0d, 0x55, 0x0e, 0x1a,
	0x8d, 0x67, 0xd0, 0xdf, 0x7d, 0x97, 0xd5, 0x99, 0x2b, 0x65, 0xee, 0x9f, 0xc5, 0x77, 0x1a, 0xd4,
	0x9f, 0xef, 0x4e, 0xea, 0x6e, 0x95, 0xff, 0xbc, 0xbc, 0xae, 0xad, 0xbb, 0xd5, 0xda, 0xff, 0x02,
	0xce, 0x82, 0xca, 0x90, 0xfd, 0xcb, 0xc4, 0x6e, 0x5f, 0x7b, 0xbf, 0x6f, 0xd8, 0x37, 0xff, 0x4e,
	0x6f, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0x82, 0x72, 0x0b, 0xc2, 0xb3, 0x04, 0x00, 0x00,
}
